# Generated by Django 5.1.1 on 2024-11-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='attachment',
            new_name='content_file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_email',
        ),
    ]
