# Generated by Django 5.1.1 on 2024-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids_app', '0002_rename_attachment_content_content_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
