# Generated by Django 5.1.1 on 2024-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids_app', '0003_feedback_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default='', max_length=6),
        ),
    ]
