# Generated by Django 5.1.1 on 2024-11-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids_app', '0004_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='question',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
