# Generated by Django 5.1.3 on 2024-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids_app', '0005_rename_message_contact_question_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='description',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(upload_to='content/'),
        ),
    ]
